### ISSUE TITLE
Authentication log

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#177]
### Description

As part of transistion to the new cloud platform we need to create a new Authentication log.

- Result of login
- UserId/systemid/
- Timestamp
- Method
- Ip-address
- Sessionid 
- Supplier/System id

### Additional Information

As part of the requirements, we need to define

- How long can we store these logs
- Is there a difference in storage time for the different data
- 

### Tasks

- Logs

### Acceptance Criterias

- [ ] Logs every request where user logs direct in to Altinn 3 with OIDC
- [ ] Logs when Altinn 3 logins based on Altinn 2 session
- [ ] Logs when maskinporten token is exchanged
- [ ]
