### ISSUE TITLE
Feature: Implement SystemUser API in Altinn Authentication

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#232]
### Description

We need to build an API to support the administration of system users for organizations. The concept was analyzed in #200  and defined in #331

Organizations can choose to create, update, and soft delete system users. 
In the future, this might be expanded to citizens. 

These issues cover the API in Altinn Authentication to support this feature. The Persistence layer and the physical database is covered in #361 

#329 covers the system register. System_Type is a foreign key to System

The BFF will consume this API from https://github.com/Altinn/altinn-authentication-frontend/issues/23

### Tasks

We need an API that can do CRUD operations on system identities.

- [x] Create new controller
- [x] Finalize system user model (attributes!!!!)
- [x] Create API to create SystemUser
- [x] Create API to update SystemUser
- [x] Create API to delete SystemUser (soft delete)
- [x] Create API to list systems users for party
- [x] Define Persistance Interface
- [x] Implement Persistance Mock
- [x] Create needed mock data for tests
- [x] Create unit tests covering the API methods. Needs to cover authorization.  (PDP Mock can be copied from Access management)
- [x] Configure authentication & authorization for API
- [x] Update APIM with API (products?)
- [x] #369
- [x] #445 
- [x] Documenation updated: https://[docs.altinn.studio/authorization/architecture/authorizationbff.drawio.svg](https://docs.altinn.studio/authorization/architecture/authorizationbff.drawio.svg)
SystemUserObject stored in database

- [x] #595

- [x] #607

```json

{
"id" : "37ce1792-3b35-4d50-a07d-636017aa7dbd",
"title": "Nytt regnskapsystem",
"description": "Systemet som vi har kjøpt hos Visma. Kai og Guri vet alt om dette systemet.",
"systemType": "visma_tax",
"ownedByParty": 234654,
"created": "2023-01-01",
"isDeleted": false
}

```

## Acceptance criteria

- [x] An  organization can only have one systemuser connected to a specific systemType
- [x] Only systems admin for org is allowed to perform CRUD operations
- [x] Deleted system users are not listed in list
