### ISSUE TITLE
Build SecurityLog component

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#233]
### Description

The security log component will be the component responsible for adding logs to database for authorization and authentication. 

See #177 for architecture

This issue defines the development tasks for this

### Tasks

- [ ] Setup new GIT repository for securitylog
- [ ] Setup .Net API project for Security Log
- [ ] Create Endpoint for Login Authentication log (post)
- [ ] Setup security log database in Azure (should it be totally separate)?
- [ ] Setup storage  queue for Loging Authentication events
- [ ] Setup storage queue for login authorization events
