### ISSUE TITLE
Notification about depreciation of Altinn-koder

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#261]
# Description

Add notification to the logon page for Altinn-koder that the authentication method is depricated and will be removed from the portal when we move to the new Id-porten environment at [date]

-------

## Text ui/Authentication
Bokmål
Fra oktober 2023 er det ikke lenger mulig å logge inn med  Altinn kodebrev, SMS kode eller Kun passord . Les mer om andre måter du kan logge inn på [her](https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/).

Nynorsk
Frå oktober 2023 er det ikkje lengre mogeleg å logge inn med Altinn kodebrev, SMS kode eller Kun passord. Les meir om andre måtar du kan logg inn på [her](https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/).

Engelsk
From October 2023, it will no longer be possible to log in with Altinn code lette,r SMS or passwords. Read more about other ways you can log in [here](https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/).

-----------

## Text Alternativ innlogging i Altinn 
Bokmål
Fra oktober 2023 er det ikke lenger mulig å logge inn med sms, passord, virksomhetssertifikat eller koder fra kodebrev. Vi anbefaler at du bruker MinID eller annen innloggingsmetode på ID-porten.
 
Dette gjelder ikke maskin til maskin-kommunikasjon. Der vil det fortsatt være mulig å logge inn med virksomhetssertifikat. Det vil også være mulig å logge inn med sms, passord og koder fra kodebrev frem til de forskjellige Altinn 2 programmeringsgrensesnittene fases ut.

For test anbefaler vi å bruke testbrukere fra [Tenor]( https://www.digdir.no/felleslosninger/tenor-testdatasok/1284)

Nynorsk 
Frå oktober 2023 er det ikkje lengre mogeleg å logge inn med sms, passord, virksomheitsertifikat eller koder frå kodebrev. Vi anbefalar at du bruker MinID eller annan innloggingsmetode på ID-porten.

Dette gjeld ikkje maskin til maskin-kommunikasjon. Der vil det framleis vere mogeleg å logge inn med virksomheitssertifikat. Det vil også vere mogeleg å logge inn med sms, passord og koder frå kodebrev fram til dei ulike Altinn 2 programmeringsgrensesnitta vert fasa ut. 

For test anbefaller me å bruke testbrukarar frå [Tenor](https://www.digdir.no/felleslosninger/tenor-testdatasok/1284)

Engelsk 
From October 2023, it will no longer be possible to log in with SMS, password, business certificate or codes from code letters. We recommend that you use MinID or another login method through ID-porten. 

This does not apply to machine-to-machine communication where it will still be possible to log in with a business certificate. It will also be possible to log in with SMS, passwords and codes from code letters until the various Altinn 2 APIs are phased out.
 
For testing, we recommend using test users from [Tenor](https://www.digdir.no/felleslosninger/tenor-testdatasok/1284)

```[tasklist]
### Tasks
- [x] Varseltekst for Altinn kodebrev, SMS og Kun passord på https://www.altinn.no/ui/Authentication
- [x] Informasjonstekst på [Alternativ innlogging i Altinn](https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/)
- [x] Informasjonstekst på https://www.altinndigital.no
- [x] Informasjonstekst på docs.altinn.studio
```
