### ISSUE TITLE
Implement authentication event logging in authentication component

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication#305]
### Description

Each authentication request must be logged as an authentication event to the audit-log component. Considering the performance, each event will be written to a storage queue and a function app will process the queue and send the event to the audit log component to be stored in the database.

### Tasks

- [x]  write the authentication event to the storage queue 
- [x] Implement feature flag for event logging
- [ ] Deploy til at environment with feature flag on for testing
- [ ] Identify areas in the authentication component to implement event logging

### Acceptance Criteria

- [ ] Each authentication request is saved as an authentication event
- [ ] Refresh action is registered as an authentication event with specific authentication event type
- [ ] Exchanging external token is registered as an authentication event with specific authentication event type
- [ ] Authentication of altinn studio token is registered authentication event with specific authentication event type
