### ISSUE TITLE
Update text on Altinn login and Enterprise certificate

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#335]
### Description

Need to update the notification about changes in Altinn and Enterprise certificate login, in production, since the removal of the Iloginmethodes has been postponed

**New text  Altinn login**

Bokmål 
Fra 23. november 2023 vil det ikke lenger være knapp i ID-porten som tar deg til denne påloggingssiden. Har du fremdeles behov for å bruke Altinn kodebrev, SMS kode eller Kun passord må du etter denne datoen bruke følgende lenke: https://www.altinn.no/ui/Authentication.  

Engelsk
From November 23, 2023, there will no longer be a button in the ID-porten that takes you to this login page. If you still need to use Altinn code letter, SMS-code, or password only, you must use the following link after this date: https://www.altinn.no/ui/Authentication.

Nynorsk
Frå 23. november 2023 vil det ikkje lenger vere ein knapp i ID-porten som fører deg til denne innloggingssida. Dersom du framleis treng å bruke Altinn kodebrev, SMS-kode eller Kun passord, må du etter denne datoen bruke følgjande lenkje: https://www.altinn.no/ui/Authentication.

**New text Enterprise certificate**

Teksten legges her:
https://www.altinn.no/hjelp/innlogging/
https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/

Bokmål
Fra 23. november 2023 vil det ikke lenger være knapp i ID-porten som tar deg til denne påloggingssiden. Har du fremdeles behov for å bruke virksomhetssertifikat må du etter denne datoen bruke følgende lenke:  https://www.altinn.no/ui/Authentication/EnterpriseIdentified.  

Engelsk 
From November 23, 2023, there will no longer be a button in the ID-porten that takes you to this login page. If you still need to use a enterprise certificate, you must use the following link after this date: https://www.altinn.no/ui/Authentication/EnterpriseIdentified.

Nynorsk
Frå 23. november 2023 vil det ikkje lenger vere ein knapp i ID-porten som fører deg til denne innloggingssida. Dersom du framleis treng å bruke eit verksemdssertifikat, må du etter denne datoen bruke følgjande lenkje: https://www.altinn.no/ui/Authentication/EnterpriseIdentified.

**New text help-pages**

Bokmål 
Fra 23. november 2023 vil knappen "Gå videre til flere innloggingsmetoder" erstatters med knappen "Logg inn uten fødselsnummer/D-nummer". Innlogging med Altinn kodebrev, SMS-kode eller kun passord samt virksomhetsbruker vil på sikt fjernes.  Vi anbefaler at du bruker MinID eller annen innloggingsmetode via ID-porten.

Dersom du ikke har mulighet til dette vil du inntil videre finne innlogging med Altinn kodebrev, SMS kode eller passord [her](https://www.altinn.no/ui/Authentication)  og Virsomhetssertifikat [her](https://www.altinn.no/ui/Authentication/EnterpriseIdentified)

Innloggingen endres kun på altinn.no og gjelder ikke maskin til maskin-kommunikasjon (regnskap- og lønnssystem). Der vil det fortsatt være mulig å autentisere seg med virksomhetssertifikat.  Det vil også være mulig å logge inn på regnskap- og lønnssystem med Altinn kodebrev og SMS-Kode frem til dette etter hvert fases ut.

Engelsk

From November 23, 2023, the button "Proceed to more login methods" will be replaced with the button "Log in without a birth number/D-number." Logging in with Altinn code letter, SMS-code, or password alone, as well as enterprise certificate, will eventually be phased out. We recommend using MinID or another login method via ID-porten.

If you do not have the option to do this, you can still find login options with Altinn code letter, SMS-code, or password [here](https://www.altinn.no/ui/Authentication) and Enterprise certificate [here](https://www.altinn.no/ui/Authentication/EnterpriseIdentified) for the time being.

This login change only applies to altinn.no and does not affect machine-to-machine communication (accounting and payroll systems). It will still be possible to authenticate with a enterprise certificate in those systems. It will also be possible to log in to accounting and payroll systems with Altinn code letters and SMS codes until they are phased out gradually.

Nynorsk
Frå 23. november 2023 vert knappen "Gå videre til fleire innloggingsmetodar" erstatta med knappen "Logg inn utan fødselsnummer/D-nummer." Innlogging med Altinn kodebrev, SMS-kode eller berre passord, samt verksemdssertifikat, vil etter kvart bli fasa ut. Vi anbefalar at du brukar MinID eller ein annan innloggingsmetode via ID-porten.

Dersom du ikkje har moglegheit til dette, kan du framleis finne innloggingsalternativ med Altinn kodebrev, SMS-kode eller passord [her](https://www.altinn.no/ui/Authentication) og Føretakssertifikat [her](https://www.altinn.no/ui/Authentication/EnterpriseIdentified) inntil vidare.

Denne endringa i innlogging gjeld berre for altinn.no og påverkar ikkje maskin-til-maskin-kommunikasjon (rekneskap- og lønssystem). Det vil framleis vere mogleg å autentisere seg med verksemdssertifikat i desse systema. Det vil også vere mogleg å logge inn på rekneskap- og lønssystem med Altinn kodebrev og SMS-kode fram til dei gradvis vert fasa ut.

### Tasks

- [x] Update text for Altinn code letter, sms and password only
- [x] Update text for Enterprise certificate
- [x] Update help pages at Altinn.no
