### ISSUE TITLE
Session Id implementation in authentication

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication#345]
### Description

It was agreed during the logging discussion that we implement session id to get overview of the user's activities for a given period of time.

### Update 06.11.2023 Discussion Outcome

Authentication requests via idporten/maskinporten/3rdparty integrations return a response with a sessionid (standard claim attribute for sessionid is "jti"). This claim will be saved in Authentication event log as external session id. An altinn session id will also be generated and saved as sessionid. So the following information will be saved in the event log

- sessionid
- external session id
- externaltokenissuer
- subscriptionkey

### Tasks

- [x] Generate sessionid as a uuid
- [x] Introduce sessionid as a claim in the token
- [x] Update the event logging code to map the generated sessionid to the authenticationevent
- [x] Update the event logging code to map the external sessionid to the authenticationevent
- [x] Update the authenticationevent model to include new properties sessionid, externalsessionid, externaltokenissuer, subscriptionkey
- [x] Update the event logging in authorization component to map the the session id from claim to the authorizaion event
- [x] Update unit tests

### Acceptance Criteria

- [ ] A session id is generated when not found for each authenticationrequest
- [ ] Session id is mapped to the sessionid proeprty
- [ ] External session id claim is mapped to the external sessionid proprety
- [ ] New properties are added to the authenticationevent model
