### ISSUE TITLE
Create API for systemprovider iniated systemuser creation

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#359]
### Description

Altinn needs to expose an API where system vendors can register a request to create a system user. 

### Additional Information

A request would need to contain the following.

- The entity that would be requested to create a system (orgnumber/ssn)
- The system
- The list of resources to get rights for

The data for request needs in addition, information about when it was created. It needs a unique request ID. 

### Tasks

- [x] Create API for the creation of system user request
- [x] Create a table for requests
- [x] Create API to present request

### Acceptance Criteria

- [ ] System vendor can register a system user creation request
- [ ] System vendor can define the unit for the system user 
- [ ] System needs to define the system that should be connected to the system user
- [ ] Request should be made with the same organizations owning the system

**Comment by ekorra** [comment]
Levert i forbindelse med https://github.com/Altinn/altinn-authentication/issues/544
