### ISSUE TITLE
Setup database / persistence layer in Altinn Authentication for systemuser

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#361]
### Description

We must define the database, schema, tables, functions, and persistence layer.  This will be used by API defined in #232 

We will set up a test server/database in Azure during development.  PostgreSQL will be used

When finalized we need to assign https://github.com/Altinn/altinn-authentication/issues/360 to Altinn Core team to define in Terraform (server/database)

### Additional Information

A new systemUser table will be created to support this. 

Suggestion for table structure. 

public guid id
public int ownedByParty // PartyId of the unit owning entity  
public string title // User friendly 
public string description // User friendly description of the 
public dateTime created // When the system was created
public string systemType // Reference to a specific system type. "Visma Regnskap"
public string clientId // Reference to own clientID in maskinporten. TODO. Need to investigate this further
public bool IsDeleted // soft delete of system user

- [ ] Create authentication server + authentication database. The task to the core for different environments
- [ ] Set up db scripts for table and stored procedures
- [ ] Make sure backup is enabled

### Tasks

- [ ] Define name for database server / database. Update #360 
- [ ] Define Table and Schema for system user
- [ ] Define functions for crud operations
- [ ] Setup persistence layer in Altinn Authentication
- [ ] Setup stored procedures/functions in Yuniql 
- [ ] Create persistence Mock for Altinn Authentication
- [ ] Create Persistence Mock test data for Altinn Authentication

### Acceptance Criteria

- [ ] Tables and structures in place automatically when deployed in environments
- [ ] All methods have a functions

**Comment by ekorra** [comment]
Lukker denne da den er levert gjennom andre issues
