### ISSUE TITLE
Configure IpAddress forwarding on the api management and traefikk tool

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication#372]
### Description

Auditlog requires that we log the client's ipaddress. Right now, we don't have the configuration in the Api Management/traefikk for forwarding the ipadress to the platform components.

### More information
api management:
https://learn.microsoft.com/en-us/azure/application-gateway/how-application-gateway-works#modifications-to-the-request
Application gateway inserts six additional headers to all requests before it forwards the requests to the backend. These headers are x-forwarded-for, x-forwarded-port, x-forwarded-proto, x-original-host, x-original-url, and x-appgw-trace-id. The format for x-forwarded-for header is a comma-separated list of IP:port.
traefik:

### Tasks

- [x] Configure Apimanagement to forward the ipadress of the client
- [x] Configure traefikk to forward the ipadress further to the platform components

### Acceptance Criteria

- [ ] Client ipadress is accessible in the platform component via ["X-Real-IP"] or ["X-Forwarded-For"]

**Comment by bengtfredh** [comment]
PR to allow headers to be forwarded to pods merged in platform infra code.
Client ip will be added as number 2 to header "X-Forwarded-For"
Rolled out to AT21 now for you to test and verify

**Comment by acn-dgopa** [comment]
@bengtfredh the auditlog test environment is setup against the At22 platform components. Can you roll out the change to AT22?

**Comment by bengtfredh** [comment]
@acn-dgopa @simon-ellefsen will roll out update in AT22

**Comment by acn-dgopa** [comment]
@bengtfredh tested ok
