### ISSUE TITLE
PostGress database with the SystemUser table

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication#379]
10 Nov: change SystemUser model name to AltinnSystemIntegration ? Because SYSTEM_USER is a reserved keyword in Postgres db.

To store the SystemUsers, see #369, we need a new PostGress db.

```[tasklist]
### Development
- [x] Write Sql : Create AltinnSystemIntegration for a PartyId
- [x] Write Sql : Get AltinnSystemIntegration by unique Id
- [x] Write Sql : Get all AltinnSystemIntegration for a PartyId
- [x] Write Sql : Set DeleteFlag on a AltinnSystemIntegration with unique Id
- [x] Write Sql : Update AltinnSystemIntegration by unique Id (replace or field by field?)
```

```[tasklist]
### Integration Tests
- [x] Add test project to run postgres db calls in a temp docker image
- [x] Chore: rewrite to global fixture
```

```[tasklist]
### Environment
- [x] Create a new db in Dev ( created db in docker image using Testcontainer )
- [x] Deploy to AT ( moved task to other Issue)
- [x] Deploy to TT02 ( moved task to other Issue)
```

```[tasklist]
### Dependencies and Prerequisites
- [x] Model is finalized, see issue: https://github.com/Altinn/altinn-authentication-frontend/issues/8
- [x] current model name: altinn_system_integration, pr 11. Nov 2023
```

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authentication/pull/382
- [ ] https://github.com/Altinn/altinn-authentication/pull/432
```

**Comment by simen-rekkedal** [comment]
SimenR
  [2:25 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699622753794039)
ifølge denne doc'en så er SYSTEM_USER reserved keyword i postgres
https://www.postgresql.org/docs/current/sql-keywords-appendix.html
kanskje kalle det noe annet i db?

PostgreSQL DocumentationPostgreSQL Documentation
[Appendix C. SQL Key Words](https://www.postgresql.org/docs/current/sql-keywords-appendix.html)
Appendix&nbsp;C.&nbsp;SQL Key Words Table&nbsp;C.1 lists all tokens that are key words in the SQL standard and in PostgreSQL 16.1. Background …
Yesterday at 2:01 PM (50 kB)
https://www.postgresql.org/docs/current/sql-keywords-appendix.html






New


runetl
  [2:35 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699623331575169)
hehe. Ja, Det er nok best da. Spørsmåler om f.eks ALTINNSYSTEM_USER eller APISYSTEM_USER blir for nært og man da må speile det andre steder også


SimenR
  [2:36 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699623370580469)
altinn_integration ?


runetl
  [2:38 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699623537373039)
Ja, det kan fungere det også. Kan jo ta det i første omgang. Får skrive på proc som oppretter at system_user var ulovlig. Jeg burde tenkt på det før


SimenR
  [2:49 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699624178088169)
eller altinn_authorization_integration ?


runetl
  [2:50 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699624202924909)
altinn_system_integration


SimenR
  [2:52 PM](https://altinndevops.slack.com/archives/C05U72ZQLVA/p1699624362510169)
jeg bruker altinn_system_integration i koden nå, så får vi ta en search and replace senere om vi ombestemmer oss

**Comment by simen-rekkedal** [comment]
Regarding the Dependency on the modeling, we move forward with the model the way it is now. And any new changes will be resolved in new Issues.

**Comment by simen-rekkedal** [comment]
Regarding the Environment, we close this Issue now, and move the tasks for CI/CD and test environments to a new Issue.
