### ISSUE TITLE
Refactor authentication controller in altinn-authentication

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication#380]
### Description

Constructor of Authentication Controller takes in more than recommended number of parameters (8). This causes some issues with sonar quality linting as well as makes the controller complex to maintain. 

### Tasks

- [ ]  Refactor authentication controller to use the recommended number of input parameters in the constructor

### Acceptance Criteria

- [ ] Authentication controller is refactored
- [ ] Regression tests pass
