### ISSUE TITLE
Cleanup: remove compiler warnings, enable nullable for all projects and prevent new warnings from being added

### ISSUE THREAD

**Issue by Alxandr** [Altinn/altinn-authentication#488]
### Description

See tasks

### Tasks

```[tasklist]
- [ ] Remove all compiler warnings
- [ ] Enable nullable reference types for all projects (including test projects)
- [ ] Update CI to run with WarnAsError
```
