### ISSUE TITLE
Scopes for Portal users

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#500]
### Description

For API we need to validate scopes. For portal users there is not natural that user accept scopes when accessing throug portal.

To solve this we need to add scopes when creating a AltinnStudioRuntime cookie  

### Additional Information

What about dialogporten?

### Tasks

- [x] Define scope to use for Portal
- [x] Update authentication to add scope for logins that is comming from Altinn 2
- [x] Legg til userUID i token

**Comment by TheTechArch** [comment]
This task is completed. IS in production
