### ISSUE TITLE
Leveranse 1: Sluttbrukerstyrt opprettelse

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#525]
# Beskrivelse

Etter leveranse skal følgende funksjonalitet være tilgjengelig 

**Ressurseier**
Ressurseier melder fra til Digdir hvilke tilagangspakkker ressursen trenger slik at Digdir kan legge dette til i listen over tilgangspakker. 
Ressurseier oppretter Generisk Autorisasjonsressurs i Ressursregisteret, i policy legger han til nødvendige enkeltrettigheter og eventuelt fremtidig behov for tilgangspakker samt velger at ressursen skal kunne brukes med "Enterprice bruker"
Ressurseier lager eller oppdaterer PDP integrasjon som kan bruke systembrukerid som parameter

**Fagsystemleverandør**
Fagsystemleverandør melder inn systemnavn, beskrivelse samt hvilke enkeltrettigheter systemet trenger
Digdir oppretter dette i systemregisteret 

**Sluttbruker**
Sluttbruker oppretter Systembruker ved å gå inn i Altinn studio 

# Hva skal leveres
```mermaid
sequenceDiagram
    actor R as Ressurseier
    actor F as Fagsystemleverandør
    
    R->>Maskinporten: Opprett scopes og gi tilganger
    Maskinporten-->>R:OK
    R->>Altinn: Opprett ressyrs, sett autorisasjonsregler
    Altinn-->>R:OK
    F->>+Maskinporten: Opprett integrasjon
    Maskinporten-->>-F: client_id
    Note over F,Altinn: Fagysystemleverandør kontakter Altinn<br/>Atinn oppretter fagystem i systemregisteret
    F->>+Altinn: Opprett fagsystem(orngr, client_id, systemnavn, beskrivelse)
    Altinn-->>F: OK
    actor S as Sluttbruker
    S->>Altinn: Opprett systembruker (orgnr, fagsystem)
    Altinn-->>S:OK
```

## In scope

- Systemregister
- Manuell opprettelse av fagsystem i systemregister
- Brukergrensesnitt for Sluttbrukerstyrt opprettelse
- Delegering av enkeltrettigheter systembruker
- Slette systembruker
- Maskinporten API
- Ressurseier kan autorisere systembruker via PDP

## Akseptansekriterier

- [ ] Fagsystem skal kunne legge inn i systemregisteret
- [x] Registrerte systemer vises i nedtreksliste i Altinn
- [ ] Bemyndiget person hos sluttbrukervirksomhet kan opprette systembruker i GUI i Altinn
- [ ] For å kunne opprette en systembruker må bruker ha tilgangstyring rettighet samt rettighet for de tjenestene som systemet krever
- [ ] Gitt clientId og  orgnr til eier av systembruker kan Maksinporten kan gjøre oppslag mot API for å hente systembrukerinformajon for gitt relasjon
- [ ] Gitt oppslag mot maskinporten hvor fagsystem ber om  systembrukertoken med orgnr til eier av systembruker, maskinporten klient-id og at denne relasjonen finnes mottar fagsystem systembrukertoken

```[tasklist]
### Test
- [x] AK1: Fagsystem skal kunne legge inn i systemregisteret  [INT, ETE]
- [x] AK2:  Registrerte systemer vises i nedtreksliste i Altinn
- [x] AK3: Bemyndiget person hos sluttbrukervirksomhet kan opprette systembruker i GUI i Altinn [INT, PW]
- [x] AK4: Gitt clientId og  orgnr til eier av systembruker kan Maksinporten kan gjøre oppslag mot API for å hente systembrukerinformajon for gitt releasjon [INT, ETE]
- [ ] AK5: Gitt oppslag mot maskinporten hvor fagsystem ber om  systembrukertoken med orgnr til eier av systembruker, maskinporten klient-id og at denne relasjonen finnes mottar fagsystem
```

## Design
[Design i Figma](https://www.figma.com/design/qWEscJDVrA2gDP6oTI4Dfm/Team-Tilgangsinfo?node-id=1502-97989&t=RMOqnZ0IA1WsJlpw-1)

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-authentication/issues/529
- [ ] https://github.com/Altinn/altinn-resource-registry/issues/409
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/257
- [x] Maskinporten API
- [x] PDP oppslag med systembruker
- [ ] https://github.com/Altinn/altinn-authentication/issues/664
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/256
- [ ] https://github.com/Altinn/altinn-authorization/issues/868
- [ ] https://github.com/Altinn/altinn-authentication/issues/670
```

```[tasklist]
### Avhengigheter
- [ ] https://github.com/Altinn/altinn-access-management/issues/698
```

```[tasklist]
### Juridisk
- [ ] https://github.com/Altinn/altinn-authentication/issues/592
- [ ] https://github.com/Altinn/altinn-authentication/issues/604
```

```[tasklist]
### Testplan
- [ ] https://github.com/Altinn/altinn-authentication/issues/599
```

**Comment by Nyeng** [comment]
Testet manuelt. 

Todo - bør vurdere Playwright-test av denne.

**Comment by Nyeng** [comment]
Nå finnes det også Playwrighttester for denne. 

https://github.com/Altinn/altinn-authentication-frontend/actions/workflows/scheduled-playwright.yml

Lukker denne.
