### ISSUE TITLE
Leveranse 2: Leverandørstyrt opprettelse

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#544]
# Beskrivelse

Fagsystemleverandør skal selv kunne opprette fagsystem i systemregisteret via API. 
Etter systemet er opprettet kan fagsystemleverandør initiere opprettelse av systembruker for en gitt virksomhet. 
Person med nødvendige rettigheter i gitte virksomhet kan godkjenne opprettelsen av systembrukeren med forespurte rettigheter i Altinn
Når systembrukeren er opprettet vises systembrukeren for sluttbruker på samme i Altinn måte som ved sluttbrukerinitiert  opprettelse. 

# Hva skal leveres

```mermaid
sequenceDiagram
    actor F as Fagsystemleverandør
    F->>+Maskinporten: Opprett integrasjon
    Maskinporten-->>-F: client_id
    F->>+Altinn: Opprett fagsystem(orngr, client_id, systemnavn, beskrivelse)
    Altinn-->>F: OK
    actor S as Sluttbruker
    S->>+Fagsystem: Opprett systembruker 
    Fagsystem->>Altinn: systembrukerforespørsel(orgnr, rettighet)
    Altinn-->>Fagsystem: systembrukerforespørsel_id, url 
    Fagsystem-->>S:redirect(url, systembrukerforespørsel_id)
    S->>+Altinn: Logon
    S->>Altinn:Godkjenn systembruker(systembrukerforespørsel_id)
    Altinn->Altinn: Logout Sluttbruker
    Altinn-->>-S:redirect
    S-->>Fagsystem:redirect
    Fagsystem-->>-S:OK
    Fagsystem->>Altinn:Hent status(systembrukerforespørsel_id)
    Altinn-->>Fagsystem: OPPRETTET
```

### In scope

Avgjøre nødvendige scopes for tilgang til
API for opprettelse av system i systemregister
API for initiering av opprettelse av systembruker
Brukergrensesnitt godkjenning av systembruker opprettelse
API for status på opprettelse

### Out of scope

Bruk av Altinn Events for status på Systembruker
Endring av rettigheter på opprettet system (ved behov for endringer kontaktes altinn slik at dette endres manuelt)
Varsling ved endring av rettigheter
Vitelisting av leverandører

### Definition of Ready
- [ ] Hensikt/Problemet
- [ ] Hva skal løses -> In scope / out of scope
- [ ]  Intensjon/mål
- [ ] Akseptansekriterier
- [ ] Juridiske/andre avklaringer
- [ ] Avhengigheter
- [ ] status
- [ ] Beslutninger
- [ ] Innsiktsarbeid
- [ ] Designskisse, flytbeskrivelser, løsningsbeskrivelser, WCAG vurderinger
- [ ] Trusselvurdering/modellering
- [ ] QA på foreslått løsning- Tres Amigos
- [ ] Sikre felles forståelse
- [ ] Kost /nyttevurdering
- [ ] Tidsestimat/kompleksitet
- [ ] Prioritering/deadline
- [ ] Strategi for kommunikasjon utad
