### ISSUE TITLE
Leveranse 4: Tilgangspakker

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#547]
### Description

Støtte tilagngspakker for Systembruker

### In scope

Mulig for fagsystemleverandør å registere behov for tilgangspakker for system i systemregisteret.
Gjelder både for opprettelse av nye systemer og ending på allerde registrerte

## Akseptansekriterier

**AK1 - Legge til system med tilgangspakke**
GITT at system har behov for tilganspakke 
NÅR dette skal legge sil i systemregisteret 
SÅ kan nødvendige tilgangspakker angis i systemopprettelsesforespørselen
OG systemet blir opprettet med disse

AK2 - Opprette systembruker med leverandørstyrt flyt 
GITT at sysetemleverandør vil opprette systembruker med leverandørstyrt flyt
OG han angir tilganspakker innenfor det som er angitt for systemet 
SÅ kan bruker godkjenne opprettelsen av dette
OG sytembruker blir opprettet

AK3 - Systembrukerrequest med feil tilgangspakker
GITT at systemleverandør vil opprette systembruker for kunde
OG angir flere tilgangspakker i requesten enn det som er registrert på systemet
SÅ får systemleverandør feilmelding fra APIet

AK4 - Opprette sysystembruker med sluttbrukerstyrt flyt
GITT at sluttbruker ønsker opprettet systembruker for gitt system
OG han velger dette systemet i systemoversikten i altinn brukergrensesnitt
OG han har nødvendige rettigheter til å opprette systembrukeren
SÅ blir det opprettet systembruker med samme tilgangspakker som systemet i systemregisteret

AK5 - Endre tilgangspakker eksisterende systembruker
GITT at systemleverandør ønsker endre tilgangspakker på eksisterende systembruker
SÅ kan han opprette request for dette
OG sluttbruker godkjenner denne requesten 
SÅ endres tilgangpakkene for gitt systembruker

AK6 - Endret tilgangspakke
GITT at systembruker er satt opp med en tilgangspakke
OG at det legges til en enkeltrettighet i denne tilgangspakken
SÅ skal systembruker nå også ha denne tilgangen

### Oppgaver
- [x] https://github.com/Altinn/altinn-authentication/issues/959
- [x] https://github.com/Altinn/altinn-authentication/issues/960
- [x] https://github.com/Altinn/altinn-authentication/issues/1041

Avhengigheter
- API for å delegere tilgangspakker til systembruker for gitt aktør
- API for å slette delegering tilgangspakker til systembruker for gitt aktør
- API for å slå opp tilgangspakker en systembruker har  for gitt aktør
- API for å vise hvilke ressurser en tilgangspakke består av. 
- API for å vise hvilke enkeltilganger en systembruker har for en aktør.

**Comment by Nyeng** [comment]
Ref grooming - @ekorra Nevne med en setning at allerede når vi legger til tilgangspakker i Systemregisteret, så må vi gjøre en validering på at tilgangspakken er delegerbar (uten å vite hvor mange tilgangspakker som vil ha den definisjonen).
