### ISSUE TITLE
Godkjenn/avvis systembruker

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#573]
# Overordnet beskrivelse
Fagsystemleverandør skal kunne tilby funksjonalitet der en bruker sitter i fagsystemer, trykker på knapp for opprettelse av systembruker, og tas inn i Altinn for å godkjenne opprettelsen

# Definisjoner

# Hva skal leveres
Gitt registrert system i systemregisteret og en opprettet systembrukerforespørsel kan fagsystemer gensere som tar bruker til side for godkjenning av systembrukeropprettelse i Altinn. Bruker presenteres her med informasjon om systemet og rettigheter gis til systembrukeren. Dersom bruker godkjenner opprettelse redirectes hen tilbake til systemet han kom fra. 
Dersom bruker avbryter havner han tilbake i systemet han kom fra
Ved begge tilfeller oppdateres status på forespørselen. Fagsystem kan sjekke status i eget API
Ved begge tilfeller logges bruker automatisk ut av Altinn

# Out of scope
- StatusAPI
- Status events

# Avklaringer
- Hva skjer ved "nei jeg gir ikke fullmakt"
- Hvilke statuser har vi 
- Hva skjer etter du har godkjent / avslått

# Akseptansekriterier
- Forespørsel må åpnes med unik url som inneholder requestID. 
- Man skal kunne godkjenne eller avvise en forespørsel
- Hvis man ikke er pålogget blir man sendt til pålogging med url som er komplett nok å returnere korrekt etter pålogging
- Bruker må ha tilgangsstyring rettighet for å åpne forespørsel til aktuell org
- Dersom bruker ikke har nødvendige rettigheter gis det melding om dette i stedet for samtykke dialog
- Vise feilmelding dersom bruker ikke er autorisert
- Sluttbruker må være innlogget med min sikkerhetsnivå 3
- Bruker må ha tilstrekkelige rettigheter (det som systemet ber om) for delegering
- Ved brukes bekreftelse skal han logges ut av Altinn 
- Lagres med extRef
- Bruker videresendes til redirect url oppgitt i forespørselen
- Det skal være mulig å avslå forespørsel, status skal da lagres (redirect også ved avslag)
- Ved aksept må autorisasjon utføres på nytt slik at man sikrer at 
      - Bruker har tilgangstyringsrettighet
      - Ressurser/rettigheter kan delegeres av bruker til systembruker
- Ved avvisning 
       - Verifiser at bruker har tilgangstyringsrettighet
- ID på systembruker settes til ID på request

## API for å hente ut info om request

Det må lages et API som brukes som grunnlag til presentere requeste
- Rettigheter ønsket
- party
- system (id, name, vendor org, description)

GET /autentication/api/v1/user/systemuser/requests/{23324}  // Tenatitivt url. Samsjekk med andre team

```jsonc
{
"system": { "id": "234324_visma_super"...},
"party" : "urn:altinn:organization:identifier-no:912399095",
"status": "new",
"singleRights" : [{
        "resource" : [{
                                 "type": "urn:altinn:resource",
                                 "value":"skd_super_mva"
                             }]
            }],
"redirectUrl": "https://visma.no/forwardPath"  // 
}
```

```[tasklist]
### Backend
- [x] API for hente info om forespørsel
- [x] API for akseptere bassert på forespørsel
- [x] API for å avvise forespørsel
```

```[tasklist]
### Frontend
- [ ] https://github.com/Altinn/altinn-authentication/issues/618
- [x] Validere av pålogget bruker mot forespørsel
- [ ] https://github.com/Altinn/altinn-authentication/issues/748
- [ ] https://github.com/Altinn/altinn-authentication-frontend/issues/323
```

```[tasklist]
### Test
- [x] Godkjenn via GUI (manuelt)
- [x] Avvis via GUI (manuelt)
```

```[tasklist]
### Tasks
- [ ] Skissere godkjenning av leverandørstyrt opprettelse
```

```[tasklist]
### Design/Frontend
- [ ] https://github.com/Altinn/altinn-authentication/issues/711
- [ ] Feilmelding ved ugyldig status
- [ ] Flyt ved avslag
- [ ] https://github.com/Altinn/altinn-authentication/issues/718
```

**Comment by Nyeng** [comment]
Sjekk ut hva som evt ikke dekkes av #807 og hva som evt må testes av child-oppgaven her for frontend

**Comment by Nyeng** [comment]
Testet ok manuelt

Utestående - godkjenne / avvise via ende til ende-test
