### ISSUE TITLE
Endre rettigheter på systembruker

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#579]
# Overordnet beskrivelse

# Definisjoner

# Hva skal leveres

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authentication/issues/580
- [ ] https://github.com/Altinn/altinn-authentication/issues/582
- [ ] https://github.com/Altinn/altinn-authentication/issues/581
```
