### ISSUE TITLE
API for opprette forespørsel

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#586]
Forspørsel inneholder orger for virksomhet, clientID og sysetmbrukerForespørselID (globalt unik), beskrivelsel
SystembrukerForespørselId er en UUID4 fagystemleverandør selv genererer
Beskrivelse er en leverandørstyrt beskrivelse slik at leverandør kan si noe mer om bakgrunnen for forespørselen. Dette for å kunne støtte multi tenant og si noe mer om case

retur
created 
url til statusapi

```[tasklist]
### Avklaringer
- [x] Skal vi ha med eller ikke ha med "RequestDescrption": "I henhold til avalte med BMX Super Software, Tilgang til Altinn " ?? Som var på gammel model, men ikke på den nyeste.
- [x] Aleksander sa under Functional Refinement at eneste måte å vite om den er helt ny på er forskjellen på 201 created og 200 ok. Men det står ikke i acceptance criteria
- [x] Request er idempotent (krever requestid fra fagsystem) (bruker systemId + orgNo + externalRef)
- [x] fjerne SystemUserId i Response siden den er lik Request Id likevel
- [x] Modellen utvides til å inneholde ConfirmUrl med dyplenka
- [x] legge til yaml.values for AT,TT osv for ConfirmUrl BaseUrl for authn.ui
```

### This is the current Request model from the Functional and Technical Refinement and Development:
```json
{
"externalRef": " 25356354325-35" // Kan settes ekstern. Må være unik pr system. Kan være Maks 64 tegn, minimum 9 tegn, tall, bindestrek, punktum, latinske bokstaver, under_score . Hvis ikke satt settes den til orgnr på den som får opprettet systembruker. 
"systemId": "234324_visma_super",
"partyOrgNo" : "urn:altinn:organization:identifier-no:912399095",
"rights" : [{
        "resource" : [{
                                 "type": "urn:altinn:resource",
                                 "value":"skd_super_mva"
                             }]
            }],

"redirectUrl": "https://visma.no/forwardPath"  // optional. Ikke sikkert dette er relevant for native løsninger. Må matche url som er satt på system. 
```   
#### We return the same model as the Request model with a 201 Ok, and add Status, our Internal Guid and ConfirmUrl
```json

{
"id": "234-234235-234" // Intern GUID
"status": "new",  // accepted, rejected, expired
"externalRef": " 25356354325-35" // Kan settes ekstern. Må være unik pr system. Kan være Maks 64 tegn, minimum 9 tegn, tall, bindestrek, punktum, latinske bokstaver, under_score . Hvis ikke satt settes den til orgnr på den som får opprettet systembruker. 
"systemId": "234324_visma_super",
"partyOrgNo" : "urn:altinn:organization:identifier-no:912399095",
"rights" : [{
        "resource" : [{
                                 "type": "urn:altinn:resource",
                                 "value":"skd_super_mva"
                             }]
            }],
"redirectUrl": "https://visma.no/forwardPath"  // optional. Ikke sikkert dette er relevant for native løsninger. Må matche url som er satt på system. 
"confirmUrl" : "https://authn.ui.at22.altinn.cloud/authfront/ui/auth/vendorrequest?id=1234-1234-1234-1234" // The URL the Vendor can direct their customer to in the Authn.UI to Approve or Reject the Request for the new SystemUser
  
```  

### Scope
 - Create Request
 - Get Request
 - db for Create / Get

```[tasklist]
### Tasks
- [x] Technical refinement
- [x] Model
- [x] Controller
- [x] Service
- [x] Db Repository
- [x] Yuniql Migrations
- [x] Return 201 Ok
- [x] Xunit tests in TestContainer with db operations ( happy path)
- [x] more Xunit tests ( including negative tests and rare cases )
```

```[tasklist]
### PRs
- [ ] #706
- [ ] https://github.com/Altinn/altinn-authentication/pull/707
- [ ] https://github.com/Altinn/altinn-authentication/pull/713
- [ ] https://github.com/Altinn/altinn-authentication/pull/714
- [ ] https://github.com/Altinn/altinn-authentication/pull/717
- [ ] https://github.com/Altinn/altinn-authentication/pull/719
- [ ] https://github.com/Altinn/altinn-authentication-frontend/pull/372
- [ ] #722
- [ ] #723
- [ ] #727
```

```[tasklist]
### Implementing these Acceptance Criteria from Parent Feature
- [x] 1 Når forespørsel opprettes så returneres komplett objekt med httpstatus 201
- [x] 2 Requester har en intern ID (GUID)
- [x] 3 Systemleverandør kan kun registere forespørsel på eget system
- [x] 4 Kan ikke be om flere rettigheter enn det som er registrert i systemregisteret
- [x] 5 Organisasjonsnummer (sluttbruker) i forespørsel må være gyldig (finnes i ER-register)
- [x] 6 Request er idempotent (krever requestid fra fagsystem) (bruker systemId + orgNo + externalRef)
- [x] 7 Systemet som registerer forespørsel må ha eget scope for å kunne administrere requester. Må defineres
- [x] 8 Systemleverandør må være autentisert med maksinporten
- [x] 9 Forespørsel uten gyldig maksinportentoken og scope avvises
- [x] 10 Leverandør kan be om færre rettigheter enn han har registrert i systemregisteret
- [x] 11 En rettighetsforespørsel som ikke er godkjent etter x tid timer ut
- [ ] 12 Leverandør skal kunne arkivere forespørsler
- [x] 13 Det må oppgis minst en rettighet.
- [x] 14 Hvis Redirect url oppgis den matche minst en url oppgitt på system. Full url uten request query string valideres. Casing og full path må være identisk.
- [x] 15 Ved posting av samme refnr flere ganger på samme system er følgende krav
- [x] 15.0. For alle scenario under skal man ALDRI endre på eksisterende request
- [x] 15.1. Hvis request ikke er slettet (softdelete) så skal alltid eksisterende request returneres med status 200 ok
- [x] 15.2. Hvis man ønsker å opprette ny request med samme ID og det finnes en fra før må leverandør (via api) først slette denne
- [x] 15.3. Hvis request slettes kan referanse gjenbrukes (softdelete abandon)
- [x] 15.4. Location header til api for hente status returneres.
- [x] 16 Det kan ikke være mulig å opprette en forespørsel med referanse som er i bruk på en aktiv systembruker
- [x] 17 Det må tilbys et API for å slette en forespørsel
- [x] 18 Sletting må autoriseres. Gir 403 hvis ikke finnes eller man ikke har tilgang. 202 accepted ellers uavhengig om den er slettet fra før
- [x] 19 Det må tilbys et API for å hente ut status på en gitt forespørsel basert på referanse + systemID
- [x] 20 Hvis man prøver å hente ut status på en request som er slettet så får man 404.
```

**Comment by ekorra** [comment]
Så vidt jeg husker var "arkivere forespørsel" ment at leverandør kunne slette/sette en forespørsel innaktiv uten at den var besvart
