### ISSUE TITLE
Update System Register Api

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication#593]
```[tasklist]
### Tasks
- [x] implementere authn-authz
- [x] Scope for Digdir admin
- [x] Guid endres til string for clientID
- [x] Utvide DB med system orgnr
- [x] Endre navn fra default rights til rights
- [x] endre system_register-system_vendor til system_vendor_orgnr
- [x] add a column in db and in model, is_visible. Used by vendors to ensure that this registered_system can only be used in Vendor-Controlled-Consent creation
- [x] Testdata i AT: Uni Micro : system: "Unimicro" , Fiken vil hete "Fiken" Lucalabs system heter Luca Regnskap
- [x] Add a foreign key relation to system register by system_internal_id
- [x] update create system such that client id is added to the maskinporten_client table
- [x] Add chcek such that it is not possible to create a system with a client id that is already mapped to another system
```
