### ISSUE TITLE
Change SystemUser table

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication#595]
```[tasklist]
### Tasks
- [x] remove client_id from system_user table
- [x] remove client_id logic from code
- [x] fix a test
- [x] remove supplier name and orgnro from db
- [x] change name from product to system
- [x] change column from hidden_internal_id to system_internal_id
- [x] modify query used in lookup by externalId (client_id) to resolve to the hidden_system_guid to find the system_user (rewrite to join)
- [x] PR: https://github.com/Altinn/altinn-authentication/pull/594
- [x] deploy to tt02
- [ ] https://github.com/Altinn/altinn-authentication/issues/616
- [x] deploy to prod
```

**Comment by Nyeng** [comment]
Lukkes etter refinement.
