### ISSUE TITLE
Update auditlog for systembruker

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authentication#891]
### Description
The auditlog component logs all the authentication and authorization events. Systemuser authorization requests must be logged in auditlog. We need to update auditlog to store the systemyuserid. Currently we don't have a field to store systemid.

### Tasks

- [x] Cofigure eventlogging for systembruker

### Acceptance Criteria

- [ ] System user authorization event is logged in the auditlog
- [ ] Information about the system user is logged in a separate database column

**Comment by Nyeng** [comment]
Vi verifiserte denne manuelt med å hente Systembrukertoken og prøve å autentisere mot et endepunkt som er satt opp til å støtte Systembrukertoken. 

Det viktigete for auditlog er bedre monitorering og alert-rule I Application insights (todo) for å overvåke at tjenesten kjører
